# Generated by Django 5.2.5 on 2025-08-11 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='round_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='round_timer_seconds',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='round',
            name='vote_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='vote_timer_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='round',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='room.room'),
        ),
    ]
