# Generated by Django 5.2.5 on 2025-08-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_round_created_at_round_round_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='round',
            name='vote_start_time',
        ),
        migrations.AddField(
            model_name='room',
            name='winner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
