# Generated by Django 5.2.5 on 2025-08-18 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_initial'),
        ('room', '0003_remove_round_created_at_remove_round_vote_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='winner',
        ),
        migrations.AddField(
            model_name='round',
            name='eliminated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.player'),
        ),
    ]
