# Generated by Django 5.2.5 on 2025-08-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_remove_room_winner_round_eliminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
